const IMOVEIS = [
  /* ═══════════════════════════════════════════════════════════
     IMÓVEIS PARA LOCAÇÃO
  ═══════════════════════════════════════════════════════════ */

  {
    slug: "jk-santa-rita",
    tipoFiltro: "apartamento",
    tipo: "JK",
    operacao: "Locação",
    titulo: "JK no bairro Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Av. Osvaldo Jardim, 842, apto 101, Santa Rita, Guaíba/RS",
    preco: "R$ 780,00/mês",
    area: "25m²",
    dormitorios: "1",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-33",
    chamada:
      "JK funcional com sacada, cozinha compacta e banheiro revestido. Próximo à BR-116, ideal para quem busca praticidade e mobilidade no bairro Santa Rita.",
    descricao: [
      "JK com aproximadamente 25 m² localizado na Av. Osvaldo Jardim, 842, apartamento 101, no bairro Santa Rita, Guaíba/RS — região com boa mobilidade urbana, próxima ao transporte público e com fácil acesso à BR-116.",
      "O ambiente é integrado no estilo JK, com boa distribuição interna que permite organizar dormitório e sala no mesmo espaço, além de cozinha compacta com pia, piso cerâmico, paredes em tons claros e boa iluminação natural.",
      "A sacada é um diferencial relevante para um imóvel compacto: proporciona maior ventilação, entrada de luz natural e sensação de amplitude — tornando o apartamento mais agradável do que opções fechadas sem área externa.",
      "O banheiro possui revestimento cerâmico, lavatório, vaso sanitário e área de banho, atendendo com funcionalidade as necessidades do dia a dia. O imóvel não possui garagem, sendo indicado para quem utiliza transporte público, bicicleta ou aplicativo.",
      "A localização é estratégica: a proximidade com a BR-116 facilita o deslocamento para diferentes bairros de Guaíba e para Porto Alegre, Eldorado do Sul e demais municípios da região metropolitana. Uma opção prática, econômica e bem situada.",
    ],
    fotos: [
      "../../img/imoveis/jk-santa-rita/foto1.jpeg",
      "../../img/imoveis/jk-santa-rita/foto2.jpeg",
      "../../img/imoveis/jk-santa-rita/foto3.jpeg",
      "../../img/imoveis/jk-santa-rita/foto4.jpeg",
      "../../img/imoveis/jk-santa-rita/foto5.jpeg",
      "../../img/imoveis/jk-santa-rita/foto6.jpeg",
      "../../img/imoveis/jk-santa-rita/foto7.jpeg",
      "../../img/imoveis/jk-santa-rita/foto8.jpeg",
      "../../img/imoveis/jk-santa-rita/foto9.jpeg",
      "../../img/imoveis/jk-santa-rita/foto10.jpeg",
      "../../img/imoveis/jk-santa-rita/foto11.jpeg",
      "../../img/imoveis/jk-santa-rita/foto12.jpeg",
      "../../img/imoveis/jk-santa-rita/foto13.jpeg",
      "../../img/imoveis/jk-santa-rita/foto14.jpeg",
      "../../img/imoveis/jk-santa-rita/foto15.jpeg",
      "../../img/imoveis/jk-santa-rita/foto16.jpeg",
      "../../img/imoveis/jk-santa-rita/foto17.jpeg",
      "../../img/imoveis/jk-santa-rita/foto18.jpeg",
      "../../img/imoveis/jk-santa-rita/foto19.jpeg",
      "../../img/imoveis/jk-santa-rita/foto20.jpeg",
      "../../img/imoveis/jk-santa-rita/foto21.jpeg",
      "../../img/imoveis/jk-santa-rita/foto22.jpeg",
      "../../img/imoveis/jk-santa-rita/foto23.jpeg",
      "../../img/imoveis/jk-santa-rita/foto24.jpeg",
      "../../img/imoveis/jk-santa-rita/foto25.jpeg",
      "../../img/imoveis/jk-santa-rita/foto26.jpeg",
      "../../img/imoveis/jk-santa-rita/foto27.jpeg",
      "../../img/imoveis/jk-santa-rita/foto28.jpeg",
      "../../img/imoveis/jk-santa-rita/foto29.jpeg",
    ],
    video: "",
    pagina: "imoveis/jk-santa-rita.html",
  },
  {
    slug: "loja-santa-rita",
    tipoFiltro: "comercial",
    tipo: "Loja Comercial",
    operacao: "Locação",
    titulo: "Loja comercial no bairro Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Av. Osvaldo Jardim, 842, Santa Rita, Guaíba/RS",
    preco: "R$ 850,00/mês",
    area: "50m²",
    dormitorios: "",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-34",
    chamada:
      "Loja de 50 m² com salão amplo, forro em gesso com iluminação, frente envidraçada e área de apoio nos fundos. Desocupada e pronta para receber seu negócio na Av. Osvaldo Jardim.",
    descricao: [
      "Loja comercial com área aproximada de 50 m² disponível para locação na Av. Osvaldo Jardim, 842, no bairro Santa Rita, Guaíba/RS — via de boa circulação, com acesso prático para clientes, fornecedores e colaboradores.",
      "O salão principal é amplo e de layout aberto, com piso cerâmico em toda a área, revestimento cerâmico parcial nas paredes, forro em gesso trabalhado com iluminação embutida e frente envidraçada que permite uso como vitrine ou identidade visual da marca.",
      "O imóvel conta com área de apoio nos fundos, adaptável para pequeno estoque, espaço administrativo ou retaguarda operacional — favorecendo a separação entre atendimento ao público e área interna de trabalho.",
      "O imóvel está desocupado, o que facilita a visitação, a negociação e a preparação do ambiente conforme a necessidade do futuro locatário. A versatilidade do espaço atende diferentes formatos de comércio e prestação de serviços.",
      "Indicada para loja de roupas ou utilidades, barbearia, salão de beleza, estética, assistência técnica, escritório comercial, ateliê, consultoria, representação ou demais atividades compatíveis com o espaço.",
    ],
    fotos: [
      "../../img/imoveis/loja-santa-rita/foto4.jpeg",
      "../../img/imoveis/loja-santa-rita/foto5.jpeg",
      "../../img/imoveis/loja-santa-rita/foto6.jpeg",
      "../../img/imoveis/loja-santa-rita/foto7.jpeg",
      "../../img/imoveis/loja-santa-rita/foto8.jpeg",
      "../../img/imoveis/loja-santa-rita/foto9.jpeg",
      "../../img/imoveis/loja-santa-rita/foto10.jpeg",
      "../../img/imoveis/loja-santa-rita/foto11.jpeg",
      "../../img/imoveis/loja-santa-rita/foto12.jpeg",
      "../../img/imoveis/loja-santa-rita/foto13.jpeg",
      "../../img/imoveis/loja-santa-rita/foto14.jpeg",
      "../../img/imoveis/loja-santa-rita/foto15.jpeg",
      "../../img/imoveis/loja-santa-rita/foto16.jpeg",
      "../../img/imoveis/loja-santa-rita/foto17.jpeg",
      "../../img/imoveis/loja-santa-rita/foto18.jpeg",
      "../../img/imoveis/loja-santa-rita/foto19.jpeg",
      "../../img/imoveis/loja-santa-rita/foto20.jpeg",
      "../../img/imoveis/loja-santa-rita/foto21.jpeg",
      "../../img/imoveis/loja-santa-rita/foto22.jpeg",
      "../../img/imoveis/loja-santa-rita/foto23.jpeg",
    ],
    video: "../../img/imoveis/loja-santa-rita/video.mp4",
    pagina: "imoveis/loja-santa-rita.html",
  },
  {
    slug: "sala-mezanino-colina",
    tipoFiltro: "comercial",
    tipo: "Sala Comercial",
    operacao: "Locação",
    titulo: "Sala comercial com mezanino na Colina",
    bairro: "Colina",
    cidade: "Guaíba/RS",
    endereco: "Colina, Guaíba/RS",
    preco: "R$ 850,00/mês",
    area: "20m²",
    dormitorios: "",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-35",
    chamada:
      "Sala de 20 m² com mezanino, frente envidraçada e banheiro privativo em ponto estratégico da Colina — próximo à Havan, Stock Center, Fórum, Prefeitura e DETRAN.",
    descricao: [
      "Sala comercial com mezanino disponível para locação na Colina, em ponto de grande circulação e visibilidade, próximo ao DETRAN, Havan, Stock Center, Fórum e Prefeitura de Guaíba — uma das regiões de maior movimento e concentração de serviços da cidade.",
      "O imóvel possui aproximadamente 20 m² muito bem aproveitados, com ambiente principal claro e versátil, frente totalmente envidraçada que favorece a iluminação natural e a exposição da marca, banheiro privativo e mezanino acessado por escada metálica em formato caracol.",
      "O mezanino é o principal diferencial do imóvel: permite melhor aproveitamento vertical do espaço para uso como área administrativa, pequeno estoque, apoio operacional ou arquivo — mantendo a área principal inteiramente disponível para atendimento, recepção ou exposição.",
      "A localização é um dos grandes atrativos. Por estar em região de fluxo intenso, próxima a órgãos públicos, comércio forte, estacionamentos e vias de circulação, o imóvel oferece exposição natural e constante, favorecendo negócios que dependem de presença e contato com o público.",
      "Indicada para escritórios, prestadores de serviços, consultórios de pequeno porte, advocacia, contabilidade, estética, despachante, financeiro, representação comercial e demais atividades compatíveis com o espaço.",
    ],
    fotos: [
      "../../img/imoveis/sala-mezanino-colina/foto.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto1.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto2.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto3.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto4.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto5.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto6.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto7.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto8.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto9.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto10.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto11.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto12.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto13.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto14.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto15.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto16.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto17.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto18.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto19.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto20.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto21.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto22.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto23.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto24.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto25.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto26.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto27.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto28.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto29.jpeg",
      "../../img/imoveis/sala-mezanino-colina/foto30.jpeg",
    ],
    video: "",
    pagina: "imoveis/sala-mezanino-colina.html",
  },
];
