const IMOVEIS = [
  {
    slug: "casa-colina",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Colina",
    bairro: "Colina",
    cidade: "Guaíba/RS",
    endereco: "Rua Belmiro Andriotti, Colina, Guaíba/RS",
    preco: "R$ 295.000,00",
    area: "117m²",
    dormitorios: "2",
    banheiros: "2",
    vagas: "",
    codigo: "612781010-33",
    chamada:
      "Casa confortável no bairro Colina, com 2 dormitórios e 2 banheiros.",
    descricao: [
      "Casa localizada na Rua Belmiro Andriotti, no bairro Colina, em Guaíba/RS.",
      "Possui 117m² de área útil, com 2 dormitórios amplos e 2 banheiros.",
      "O imóvel conta com sala de estar, cozinha bem distribuída, área de serviço coberta com churrasqueira e amplo pátio.",
      "Acabamento em porcelanato, paredes com revestimento decorativo e ar-condicionado nos dormitórios.",
      "Imóvel indicado para quem busca conforto, praticidade e bom custo-benefício em Guaíba.",
    ],
    fotos: [
      "../../img/imoveis/casa-colina/foto1.jpg",
      "../../img/imoveis/casa-colina/foto2.jpg",
      "../../img/imoveis/casa-colina/foto3.jpg",
      "../../img/imoveis/casa-colina/foto4.jpg",
      "../../img/imoveis/casa-colina/foto5.jpg",
      "../../img/imoveis/casa-colina/foto6.jpg",
      "../../img/imoveis/casa-colina/foto7.jpg",
      "../../img/imoveis/casa-colina/foto8.jpg",
      "../../img/imoveis/casa-colina/foto9.jpg",
      "../../img/imoveis/casa-colina/foto10.jpg",
      "../../img/imoveis/casa-colina/foto11.jpg",
      "../../img/imoveis/casa-colina/foto12.jpg",
      "../../img/imoveis/casa-colina/foto13.jpg",
      "../../img/imoveis/casa-colina/foto14.jpg",
      "../../img/imoveis/casa-colina/foto15.jpg",
      "../../img/imoveis/casa-colina/foto16.jpg",
      "../../img/imoveis/casa-colina/foto17.jpg",
      "../../img/imoveis/casa-colina/foto18.jpg",
    ],
    video: "",
    pagina: "imoveis/casa-colina.html",
  },
  {
    slug: "casa-bom-fim",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Bom Fim",
    bairro: "Bom Fim",
    cidade: "Guaíba/RS",
    endereco: "Rua Pedro Caldas, Bom Fim, Guaíba/RS",
    preco: "R$ 180.000,00",
    area: "70m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-32",
    chamada:
      "Casa desocupada, pronta para uso e com terreno amplo de 300m² no bairro Bom Fim.",
    descricao: [
      "Ótima casa no bairro Bom Fim, em uma região tranquila e de fácil acesso em Guaíba.",
      "Possui 70m² de área útil, com 3 quartos, 1 banheiro, cozinha ampla e sala de estar.",
      "O terreno possui 300m², oferecendo possibilidade de ampliação, paisagismo ou melhor aproveitamento externo.",
      "Imóvel desocupado, pronto para uso. Cercada por ruas asfaltadas, com fácil acesso a transporte público, escolas e serviços.",
      "Ótima opção para quem busca uma casa acessível, funcional e pronta para morar.",
    ],
    fotos: [
      "../../img/imoveis/casa-bom-fim/foto1.jpg",
      "../../img/imoveis/casa-bom-fim/foto2.jpg",
      "../../img/imoveis/casa-bom-fim/foto3.jpg",
      "../../img/imoveis/casa-bom-fim/foto4.jpg",
      "../../img/imoveis/casa-bom-fim/foto5.jpg",
      "../../img/imoveis/casa-bom-fim/foto6.jpg",
      "../../img/imoveis/casa-bom-fim/foto7.jpg",
      "../../img/imoveis/casa-bom-fim/foto8.jpg",
      "../../img/imoveis/casa-bom-fim/foto9.jpg",
      "../../img/imoveis/casa-bom-fim/foto10.jpg",
      "../../img/imoveis/casa-bom-fim/foto11.jpg",
      "../../img/imoveis/casa-bom-fim/foto12.jpg",
      "../../img/imoveis/casa-bom-fim/foto13.jpg",
      "../../img/imoveis/casa-bom-fim/foto14.jpg",
      "../../img/imoveis/casa-bom-fim/foto15.jpg",
    ],
    video: "",
    pagina: "imoveis/casa-bom-fim.html",
  },
  {
    slug: "sobrado-santa-rita",
    tipoFiltro: "sobrado",
    tipo: "Sobrado",
    operacao: "Venda",
    titulo: "Complexo com lojas e residências no Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Av. Osvaldo Jardim, 842, Santa Rita, Guaíba/RS",
    preco: "R$ 1.100.000,00",
    area: "500m²",
    dormitorios: "5",
    banheiros: "7",
    vagas: "4",
    codigo: "612781010-28",
    chamada:
      "Complexo imobiliário misto com lojas comerciais e 4 unidades residenciais, aproximadamente 80% locado, gerando renda mensal em torno de R$ 5.000,00.",
    descricao: [
      "Imóvel misto localizado no bairro Santa Rita, em posição estratégica a poucos metros da BR-116.",
      "O conjunto é composto por lojas comerciais amplas e múltiplas unidades residenciais: dois apartamentos de um dormitório, um JK e uma residência de dois dormitórios.",
      "Atualmente aproximadamente 80% locado, gerando renda mensal estimada em torno de R$ 5.000,00.",
      "Próximo ao Complexo Logístico Ellosul do Grupo Lebes e à CMPC Celulose Riograndense, dois dos maiores polos de desenvolvimento econômico da região.",
      "Construção de 2019, com 600m² totais, lote de 20x26m, 2 andares e 4 vagas de estacionamento.",
      "Excelente opção para investidores que buscam diversificação de renda, localização estratégica e valorização patrimonial contínua.",
    ],
    fotos: [
      "../../img/imoveis/sobrado-santa-rita/foto1.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto2.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto3.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto4.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto5.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto6.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto7.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto8.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto9.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto10.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto11.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto12.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto13.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto14.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto15.jpg",
      "../../img/imoveis/sobrado-santa-rita/foto16.jpg",
    ],
    video: "../../img/imoveis/sobrado-santa-rita/video.mp4",
    pagina: "imoveis/sobrado-santa-rita.html",
  },
  {
    slug: "casa-jardim-dos-lagos",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no Jardim dos Lagos",
    bairro: "Jardim dos Lagos",
    cidade: "Guaíba/RS",
    endereco: "Rua Noel Guarani, 352, Jardim dos Lagos, Guaíba/RS",
    preco: "R$ 370.000,00",
    area: "108m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-21",
    chamada:
      "Casa ampla com terreno de 330m², alicerce pronto para segundo andar e churrasqueira, próxima à Av. Ponche Verde.",
    descricao: [
      "Casa localizada na Rua Noel Guarani, no bairro Jardim dos Lagos, próxima à Avenida Ponche Verde.",
      "Possui 108m² de área construída em terreno de 330m², com alicerce já reforçado e pronto para construção do segundo pavimento.",
      "3 dormitórios amplos e iluminados, sala de estar aconchegante, cozinha funcional e banheiro social completo.",
      "Área coberta com churrasqueira, pátio generoso com possibilidade de piscina, jardim ou ampliação.",
      "Construção de 2011, bem conservada e pronta para morar. Região com academias, mercados, farmácias, escolas e transporte público próximos.",
    ],
    fotos: [
      "../../img/imoveis/casa-jardim-dos-lagos/foto1.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto2.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto3.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto4.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto5.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto6.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto7.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto8.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto9.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto10.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto11.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto12.jpg",
      "../../img/imoveis/casa-jardim-dos-lagos/foto13.jpg",
    ],
    video: "",
    pagina: "imoveis/casa-jardim-dos-lagos.html",
  },
  {
    slug: "terreno-br116-bom-fim",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Terreno no Jardim Europa — Loteamento BR-116",
    bairro: "Jardim Europa",
    cidade: "Guaíba/RS",
    endereco: "BR-116, ao lado da Scala Logística, Guaíba/RS",
    preco: "R$ 94.452,60",
    area: "165m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-19",
    chamada:
      "Terreno de 165m² no loteamento Jardim Europa, bairro planejado com alto potencial de valorização às margens da BR-116.",
    descricao: [
      "Terreno de 165m² inserido no loteamento Jardim Europa Residencial, desenvolvido pela Buriti Grupo Brasil Terrenos.",
      "Localizado estrategicamente às margens da BR-116, ao lado da Scala Logística, com acesso rápido a Porto Alegre e toda a Região Metropolitana.",
      "Bairro planejado com traçado moderno, ruas amplas, áreas verdes e espaços de lazer. Terrenos residenciais e comerciais disponíveis.",
      "Alto potencial de valorização impulsionado pelo crescimento logístico e industrial da região, incluindo o Complexo Ellosul e a CMPC Celulose Riograndense.",
      "Condições facilitadas de aquisição: entrada acessível e parcelamento próprio, sem burocracia excessiva.",
    ],
    fotos: [
      "../../img/imoveis/terreno-br116-bom-fim/foto1.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto2.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto3.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto4.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto5.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto6.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto7.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto8.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto9.jpg",
      "../../img/imoveis/terreno-br116-bom-fim/foto10.jpg",
    ],
    video: "../../img/imoveis/terreno-br116-bom-fim/video.mp4",
    pagina: "imoveis/terreno-br116-bom-fim.html",
  },
  {
    slug: "casa-coronel-nassuca",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Coronel Nassuca",
    bairro: "Coronel Nassuca",
    cidade: "Guaíba/RS",
    endereco: "Rua Maneca Paiva, 144, Coronel Nassuca, Guaíba/RS",
    preco: "R$ 250.000,00",
    area: "70m²",
    areaTerreno: "306m²",
    dormitorios: "1",
    banheiros: "2",
    vagas: "",
    codigo: "612781010-16",
    chamada:
      "Casa desocupada com terreno de 306m², espaço gourmet, varanda e amplo quintal no bairro Coronel Nassuca. Preço reduzido — oportunidade única!",
    descricao: [
      "Casa localizada na Rua Maneca Paiva, 144, no bairro Coronel Nassuca, em Guaíba/RS — região residencial tranquila em valorização, com ruas asfaltadas e fácil acesso ao centro.",
      "Possui 70m² de área construída em um lote generoso de 306m² (10x30,6m), oferecendo excelente potencial de ampliação, paisagismo ou aproveitamento externo.",
      "A planta interna distribui 7 ambientes: sala de trabalho (15m²), copa bem ventilada (8m²), sala iluminada (4m²), 1 quarto bem ventilado (8m²), 2 banheiros e área de serviço (6m²).",
      "Conta com espaço gourmet integrado, varanda gourmet coberta, jardim, gramado, quintal e vaga para motos — ideal para quem gosta de receber.",
      "Imóvel desocupado e pronto para reformar ou personalizar. Aceita pets, acessível a cadeiras de rodas, aquecimento elétrico e coleta seletiva de lixo.",
      "Localização privilegiada: perto de escolas, transporte público, hospital, farmácias, igrejas e comércio de bairro. Acesso rápido à BR e a Porto Alegre.",
    ],
    fotos: [
      "../../img/imoveis/casa-coronel-nassuca/foto1.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto2.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto3.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto4.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto5.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto6.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto7.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto8.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto9.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto10.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto11.jpg",
      "../../img/imoveis/casa-coronel-nassuca/foto12.jpg",
    ],
    video: "../../img/imoveis/casa-coronel-nassuca/video.mp4",
    pagina: "imoveis/casa-coronel-nassuca.html",
  },
  {
    slug: "terreno-colina-lorival",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Terreno no bairro Colina — Av. Lourival Luiz da Cunha",
    bairro: "Colina",
    cidade: "Guaíba/RS",
    endereco: "Av. Lourival Luiz da Cunha, Colina, Guaíba/RS",
    preco: "R$ 285.000,00",
    area: "463m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-15",
    chamada:
      "Terreno de 463m² em localização estratégica no bairro Colina, uma das áreas que mais crescem em Guaíba. Topografia plana, rua asfaltada e documentação regular.",
    descricao: [
      "Terreno localizado na Avenida Lourival Luiz da Cunha, no bairro Colina — uma das regiões de maior valorização em Guaíba/RS, com infraestrutura consolidada e crescimento contínuo.",
      "Possui 463m² de área total, com excelente aproveitamento geométrico: 25,36m de frente por 25m de lateral. Topografia predominantemente plana, o que reduz custos de implantação.",
      "Área edificável de 4.630m² viabiliza projetos residenciais de padrão elevado, empreendimentos comerciais ou mistos — atende tanto o comprador familiar quanto o investidor corporativo.",
      "Localização privilegiada: próximo à BR-116, ao centro de Guaíba, com linhas de ônibus nas proximidades (511 – Jardim dos Lagos / Colina / Centro e 501 – Pedras Brancas / Centro).",
      "O entorno conta com escolas, supermercados, farmácias, hospitais, igrejas e comércio variado, além de fácil acesso a Porto Alegre e demais polos da Região Metropolitana.",
      "Documentação regular, matrícula individual e pronto para negociação — segurança jurídica em todas as etapas da aquisição.",
    ],
    fotos: [
      "../../img/imoveis/terreno-colina-lorival/foto1.jpg",
      "../../img/imoveis/terreno-colina-lorival/foto2.jpg",
      "../../img/imoveis/terreno-colina-lorival/foto3.jpg",
      "../../img/imoveis/terreno-colina-lorival/foto4.jpg",
      "../../img/imoveis/terreno-colina-lorival/foto5.jpg",
      "../../img/imoveis/terreno-colina-lorival/foto6.jpg",
    ],
    video: "",
    pagina: "imoveis/terreno-colina-lorival.html",
  },
  {
    slug: "predio-lupicinio",
    tipoFiltro: "comercial",
    tipo: "Loja Comercial",
    operacao: "Venda",
    titulo: "Loja Comercial na Av. Lupicínio Rodrigues",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Av. Lupicínio Rodrigues, 278, Santa Rita, Guaíba/RS",
    preco: "R$ 290.000,00",
    area: "84m²",
    dormitorios: "",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-8",
    chamada:
      "Loja de 84m² em polo comercial estratégico no bairro Santa Rita, na principal avenida de Guaíba. Alta visibilidade, fluxo garantido e acesso direto à BR-116.",
    descricao: [
      "Loja comercial localizada na Avenida Lupicínio Rodrigues, 278, no bairro Santa Rita — um dos eixos comerciais e logísticos mais movimentados de Guaíba/RS.",
      "Possui 84m² de área útil distribuídos em sala/loja de 90m², banheiro com ventilação direta e despensa de 30m², além de fachada adaptável ao tipo de negócio.",
      "Pé-direito alto, infraestrutura elétrica e hidráulica instalada, acessível a cadeiras de rodas e com excelente exposição de fachada para a avenida.",
      "Localização estratégica com acesso rápido à BR-116, RS-240 e demais rodovias do estado — ideal para negócios que demandam logística, visibilidade ou atendimento ao público.",
      "O entorno concentra supermercados, bancos, farmácias, cartórios, órgãos públicos e centros de serviços, gerando fluxo constante de consumidores e profissionais.",
      "Aceita proposta e permuta. Unidade única disponível em área de alta valorização e crescimento contínuo.",
    ],
    fotos: [
      "../../img/imoveis/predio-lupicinio/foto1.jpg",
      "../../img/imoveis/predio-lupicinio/foto2.jpg",
      "../../img/imoveis/predio-lupicinio/foto3.jpg",
      "../../img/imoveis/predio-lupicinio/foto4.jpg",
      "../../img/imoveis/predio-lupicinio/foto5.jpg",
      "../../img/imoveis/predio-lupicinio/foto6.jpg",
      "../../img/imoveis/predio-lupicinio/foto7.jpg",
      "../../img/imoveis/predio-lupicinio/foto8.jpg",
      "../../img/imoveis/predio-lupicinio/foto9.jpg",
      "../../img/imoveis/predio-lupicinio/foto10.jpg",
      "../../img/imoveis/predio-lupicinio/foto11.jpg",
      "../../img/imoveis/predio-lupicinio/foto12.jpg",
      "../../img/imoveis/predio-lupicinio/foto13.jpg",
    ],
    video: "",
    pagina: "imoveis/predio-lupicinio.html",
  },
  {
    slug: "casa-santa-rita",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Rua Maceió, 855, Santa Rita, Guaíba/RS",
    preco: "R$ 320.000,00",
    area: "150m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "2",
    codigo: "612781010-11",
    chamada:
      "Casa pronta para morar no bairro Santa Rita, com 150m², 3 quartos, garagem para 2 carros, jardim e quintal amplo. Próxima ao supermercado Atual e à BR-116.",
    descricao: [
      "Casa localizada na Rua Maceió, 855, no bairro Santa Rita — região residencial bem estabelecida em Guaíba/RS, com fácil acesso à BR-116 e ao centro da cidade.",
      "Possui 150m² de área útil em lote de 300m² (10x30m), distribuídos em 10 ambientes funcionais: sala de estar (12m²), quarto principal com closet (12m² + 6m²), 2 quartos adicionais (12m² e 9m²), cozinha ampla (16m²), banheiro (4m²), despensa (4m²), garagem (20m²) e quintal aprazível (30m²).",
      "Garagem coberta para 2 veículos, jardim bem cuidado, quintal amplo e registro de gás individual — estrutura completa para o dia a dia familiar.",
      "Acessível a cadeiras de rodas, aceita pets e conta com integração ao sistema metropolitano de transporte público, incluindo a linha TM5 com conexão a Porto Alegre.",
      "Construção sólida de 1980, bem conservada e pronta para uso imediato. Região com supermercados, farmácias, escolas, igrejas e comércio variado nas proximidades.",
    ],
    fotos: [
      "../../img/imoveis/casa-santa-rita/foto1.jpg",
      "../../img/imoveis/casa-santa-rita/foto2.jpg",
      "../../img/imoveis/casa-santa-rita/foto3.jpg",
      "../../img/imoveis/casa-santa-rita/foto4.jpg",
      "../../img/imoveis/casa-santa-rita/foto5.jpg",
      "../../img/imoveis/casa-santa-rita/foto6.jpg",
      "../../img/imoveis/casa-santa-rita/foto7.jpg",
      "../../img/imoveis/casa-santa-rita/foto8.jpg",
      "../../img/imoveis/casa-santa-rita/foto9.jpg",
      "../../img/imoveis/casa-santa-rita/foto10.jpg",
      "../../img/imoveis/casa-santa-rita/foto11.jpg",
      "../../img/imoveis/casa-santa-rita/foto12.jpg",
      "../../img/imoveis/casa-santa-rita/foto13.jpg",
      "../../img/imoveis/casa-santa-rita/foto14.jpg",
      "../../img/imoveis/casa-santa-rita/foto15.jpg",
      "../../img/imoveis/casa-santa-rita/foto16.jpg",
      "../../img/imoveis/casa-santa-rita/foto17.jpg",
      "../../img/imoveis/casa-santa-rita/foto18.jpg",
    ],
    video: "",
    pagina: "imoveis/casa-santa-rita.html",
  },
];
